require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DrawingsController do

  # This should return the minimal set of attributes required to create a valid
  # Drawing. As you add validations to Drawing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DrawingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all drawings as @drawings" do
      drawing = Drawing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:drawings).should eq([drawing])
    end
  end

  describe "GET show" do
    it "assigns the requested drawing as @drawing" do
      drawing = Drawing.create! valid_attributes
      get :show, {:id => drawing.to_param}, valid_session
      assigns(:drawing).should eq(drawing)
    end
  end

  describe "GET new" do
    it "assigns a new drawing as @drawing" do
      get :new, {}, valid_session
      assigns(:drawing).should be_a_new(Drawing)
    end
  end

  describe "GET edit" do
    it "assigns the requested drawing as @drawing" do
      drawing = Drawing.create! valid_attributes
      get :edit, {:id => drawing.to_param}, valid_session
      assigns(:drawing).should eq(drawing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Drawing" do
        expect {
          post :create, {:drawing => valid_attributes}, valid_session
        }.to change(Drawing, :count).by(1)
      end

      it "assigns a newly created drawing as @drawing" do
        post :create, {:drawing => valid_attributes}, valid_session
        assigns(:drawing).should be_a(Drawing)
        assigns(:drawing).should be_persisted
      end

      it "redirects to the created drawing" do
        post :create, {:drawing => valid_attributes}, valid_session
        response.should redirect_to(Drawing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved drawing as @drawing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Drawing.any_instance.stub(:save).and_return(false)
        post :create, {:drawing => { "id" => "invalid value" }}, valid_session
        assigns(:drawing).should be_a_new(Drawing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Drawing.any_instance.stub(:save).and_return(false)
        post :create, {:drawing => { "id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested drawing" do
        drawing = Drawing.create! valid_attributes
        # Assuming there are no other drawings in the database, this
        # specifies that the Drawing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Drawing.any_instance.should_receive(:update).with({ "id" => "1" })
        put :update, {:id => drawing.to_param, :drawing => { "id" => "1" }}, valid_session
      end

      it "assigns the requested drawing as @drawing" do
        drawing = Drawing.create! valid_attributes
        put :update, {:id => drawing.to_param, :drawing => valid_attributes}, valid_session
        assigns(:drawing).should eq(drawing)
      end

      it "redirects to the drawing" do
        drawing = Drawing.create! valid_attributes
        put :update, {:id => drawing.to_param, :drawing => valid_attributes}, valid_session
        response.should redirect_to(drawing)
      end
    end

    describe "with invalid params" do
      it "assigns the drawing as @drawing" do
        drawing = Drawing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Drawing.any_instance.stub(:save).and_return(false)
        put :update, {:id => drawing.to_param, :drawing => { "id" => "invalid value" }}, valid_session
        assigns(:drawing).should eq(drawing)
      end

      it "re-renders the 'edit' template" do
        drawing = Drawing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Drawing.any_instance.stub(:save).and_return(false)
        put :update, {:id => drawing.to_param, :drawing => { "id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested drawing" do
      drawing = Drawing.create! valid_attributes
      expect {
        delete :destroy, {:id => drawing.to_param}, valid_session
      }.to change(Drawing, :count).by(-1)
    end

    it "redirects to the drawings list" do
      drawing = Drawing.create! valid_attributes
      delete :destroy, {:id => drawing.to_param}, valid_session
      response.should redirect_to(drawings_url)
    end
  end

end
